import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

type ReportData = {
  generated_at: string;
  role: string;
  totals: { all: number; by_status: Record<string, number>; by_sbu: Record<string, number> };
  top: Array<{ id: string; title: string; sbu: string; status: string; score?: { total: number; confidence: string } | null }>;
  deferred: Array<{ id: string; title: string; sbu: string }>;
  handed_off: Array<{ id: string; title: string; sbu: string; sxg_ado_id: string | null }>;
  decisions: Array<{ request_id: string; outcome: string; reviewer_alias: string; decided_at: string; notes: string | null }>;
};

export function exportReportPDF(d: ReportData) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const w = doc.internal.pageSize.getWidth();

  doc.setFontSize(20);
  doc.text("Cross-SBU Tech Debt Prioritization", 40, 60);
  doc.setFontSize(11);
  doc.setTextColor(120);
  doc.text(`Report generated ${new Date(d.generated_at).toLocaleString()} · Role: ${d.role}`, 40, 80);
  doc.setTextColor(0);

  doc.setFontSize(13);
  doc.text("Pipeline overview", 40, 120);
  autoTable(doc, {
    startY: 130,
    head: [["Status", "Count"]],
    body: Object.entries(d.totals.by_status).map(([k, v]) => [k, String(v)]),
    theme: "striped",
    headStyles: { fillColor: [30, 30, 30] },
  });

  // SBU breakdown
  let y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;
  doc.setFontSize(13);
  doc.text("By SBU", 40, y);
  autoTable(doc, {
    startY: y + 10,
    head: [["SBU", "Items"]],
    body: Object.entries(d.totals.by_sbu).map(([k, v]) => [k, String(v)]),
    theme: "striped",
    headStyles: { fillColor: [30, 30, 30] },
  });

  // Top ranked
  y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;
  doc.setFontSize(13);
  doc.text("Top 10 by score", 40, y);
  autoTable(doc, {
    startY: y + 10,
    head: [["#", "Title", "SBU", "Status", "Score", "Conf"]],
    body: d.top.map((r, i) => [
      String(i + 1),
      r.title.length > 60 ? r.title.slice(0, 60) + "…" : r.title,
      r.sbu,
      r.status,
      r.score ? String(r.score.total) : "—",
      r.score?.confidence ?? "—",
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: [30, 30, 30] },
  });

  // Decisions
  if (d.decisions.length) {
    doc.addPage();
    doc.setFontSize(13);
    doc.text("Decisions log", 40, 60);
    autoTable(doc, {
      startY: 70,
      head: [["Date", "Outcome", "Reviewer", "Notes"]],
      body: d.decisions.slice(0, 30).map((dec) => [
        new Date(dec.decided_at).toLocaleDateString(),
        dec.outcome,
        dec.reviewer_alias,
        (dec.notes ?? "").slice(0, 80),
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [30, 30, 30] },
    });
  }

  // Deferred
  if (d.deferred.length) {
    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;
    doc.setFontSize(13);
    doc.text(`Deferred (${d.deferred.length})`, 40, y);
    autoTable(doc, {
      startY: y + 10,
      head: [["Title", "SBU"]],
      body: d.deferred.slice(0, 20).map((r) => [r.title.slice(0, 80), r.sbu]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [30, 30, 30] },
    });
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(`Generated by Lovable · page ${doc.getNumberOfPages()}`, w - 40, 780, { align: "right" });

  doc.save(`tech-debt-prioritization-${Date.now()}.pdf`);
}
